spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.233.184:8848
        username: nacos  # ?????????????????
        password: 123456
      config:
        server-addr: 172.20.233.184:8848
        username: nacos
        password: 123456
        namespace: gateway
        group: DEFAULT_GROUP
        refresh-enabled: true
        file-extension: yaml
    gateway:
      routes:
      - id: query_route
        uri: https://www.baidu.com
        predicates:
        - Query=url,baidu

      - id: qq_route
        uri: https://www.qq.com
        predicates:
          - Query=url,qq
  config:
    import:
          - nacos:gulimail-gateway?group=DEFAULT_GROUP
  application:
    name: gulimail-gateway
  autoconfigure:
    exclude:
              - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 10006